import sqlite3

conn = sqlite3.connect('FAQHealth.db')
cursor = conn.cursor()

def create_tables():
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS groups (
        id_group INT PRIMARY KEY AUTOINCREMENT,
        name TEXT NOT NULL,
        grade TEXT DEFAULT NULL);''')
    
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS questions (
        id_question TINYINT PRIMARY KEY AUTOINCREMENT,
        id_group TINYINT,
        question TEXT NOT NULL,
        answer TEXT NOT NULL,
        pergunta TEXT NOT NULL,
        resposta TEXT NOT NULL,
        votes TINYINT DEFAULT 0,
        category TEXT DEFAULT NULL,
        FOREIGN KEY (id_group) REFERENCES groups(id_group));''')
    conn.commit()
    conn.close()

def insert_group():
    cursor.execute('''
        INSERT INTO groups (name, grade) VALUES
        ('Tomás Castelo, Vasco Machado, Samuel Rodrigues, Walter João e Waldir Milagre ', '2ºJ'),
        ('Ânia, Marta e Tomé', NULL),
        ('Taissa e Esperança', NULL),
        ('Pedro Lopes e Orlean Mpaka', '2ºL'),
        ('Isaac, Lara, Beatriz e Madalena', NULL),
        ('Diogo , Filipe, Rodrigo e Simão', NULL),
        ('Luana Santos e Rodrigo Silva', NULL),
        ('Maria Meireles, Diego Pernia, Rodrigo Fernandes e Filipa Cruz', '2ºL');''')
    conn.commit()
    conn.close()

def insert_questions():
    cursor.execute('''
        INSERT INTO questions (id_group, pergunta, resposta, question, answer, category) VALUES
        (1, 'Quantas horas deve dormir um jovem, por noite, para ter um sono adequado ?', 'Um sono arqueado depende muito do jovem em si, idealmente no mínimo 7-8 horas. Os atletas precisam dormir mais de 7-8 horas.', 'How many hours should a young person sleep, each night, to have adequate sleep ?', 'An acurate sleep depends very much on the young person himself, ideally at least 7-8 hours. Athletes need to sleep more than 7-8 hours.', 'Mental Health'),
        (1, 'O que fazer para ter mais ânimo a fazer exercício físico ?', 'Várias maneiras: encontrar uma coisa que goste, arranjar companhia, e tentar incluir pequenas atividades no dia a dia, por exemplo, ir a pé invés de andar de autocarro ou subir as escoados invés de andar de elevador.', 'What to do if we want to have more encouragement to exercise physically ?', 'Several ways: find something you like, get company, and try to include small activities in your daily life, for example, walking instead of taking the bus or climbing the stairs instead of taking the elevator.', 'Training'),
        (1, 'Que sinais indicam que alguém está ansioso ?', 'A ansiedade varia de pessoa a pessoa, as indicações que uma pessoa está a sofrer ansiedade são: sua mais, batimento cardíaco mais rápido, treme mais frequentemente, tem dificuldade a dormir, pode vomitar ou estar nauseado, pode falar muito. Mas a ansiedade tem pontos positivos, porque deixa os humanos alertados, mas caso a ansiedade seja em excesso pode afetar no dia a dia.', 'What signs indicate that someone is anxious ?', 'Anxiety varies from person to person, the indications that a person is experiencing anxiety are: more perspiration, the heartbeat is faster, more frequent tremors, difficulty sleeping, maybe vomit or nausea, excessive talking. But anxiety has positive points, because it alerts humans, but if anxiety is too much it can affect everyday life.', 'Mental Health'),
        (1, 'Qual impacto que o uso excessivo do telemóvel, do computador ou televisão têm na qualidade do meu sono ?', 'Os eletrônicos têm luzes azuis, dá indicação ao cérebro que é hora de acordar e não dormir e isso causa a produção de melatonina. A melatonina é a responsável pela regulação do sono.', 'What impact does the excessive use of the mobile phone, computer or television have on my sleep quality ?', 'Electronics have blue lights that give the brain indication that it is time to wake up and not sleep and this causes the production of melatonin. Melatonin is responsible for regulating sleep.', 'Mental Health'),
        (1, 'De que forma o consumo de cafeína pode afetar a qualidade do meu sono ?', 'O consumo de cafeína impede ao cérebro que não estamos cansados, o que impede de dormirmos, o que pode causar insónias, afeta a qualidade de sono da seguinte forma: demoramos mais a adormecer.', 'How can caffeine consumption affect the quality of my sleep ?', 'Caffeine consumption prevents the brain from being tired, which prevents us from sleeping, which can cause insomnia, affects sleep quality in the following way: we take longer to fall asleep.', 'Mental Health'),
        (1, 'Que medidas os jovens podem adotar para melhorar o descanso e conseguir um sono mais profundo ?', 'Para tornar um sono mais profundo devemos acordar e deitar à mesma hora, rotina antes de ir dormir, evitar o uso de ecrãs 30 minutos antes de dormir, refeições leves ao jantar e não beber cafeína 8 horas antes de dormir, os quartos tem de estar entre os 18º e os 21º graus, o quarto deve estar o mais escuro possível.', 'What measures can young people adopt to improve rest and achieve a deeper sleep ?', 'To make a deeper sleep, we must wake up and go to bed at the same time, have a routine before going to sleep, avoid using screens 30 minutes before sleeping, light meals at dinner and do not drink caffeine 8 hours before bedtime; rooms must be between 18° and 21° degrees, the room should be as dark as possible.', 'Mental Health'),
        (1, 'O que fazer quando existe dificuldade em adormecer apesar de se estar cansado ?', 'Temos de levantar, ir à casa de banho, comer alguma coisa ou beber alguma coisa leve e antes de deitar escrever num papel o que mais preocupa, e depois podemos deitar-nos.', 'What to do when there is difficulty falling asleep despite being tired ?', 'We have to get up, go to the bathroom, eat something or drink something light and before lying down write on a piece of paper what worries us most, and then we can go to bed.', 'Mental Health'),
        (1, 'De que forma é que a utilização de produtos de limpeza muito agressivos (com pH elevado ou tensioativos fortes) pode comprometer a função da barreira da pele ? E quais são os sinais de alerta ?', 'Caso usemos produtos fortes, a pele fica seca, abrindo feridas. sinais: pele vermelha, inchada, dorida, com pus, ou com comichão.', 'How is the use of very aggressive cleaning products (with high pH or strong surfactants) may compromise the function of skin barrier ? And what are the warning signs ?', 'If we use strong products, the skin becomes dry, opening wounds. signs: red skin, swollen, sore, with pus, or itchy.', 'Prevention'),
        (1, 'De que forma o stress ou a ansiedade podem influenciar o desejo sexual e/ou os afetos numa relação amorosa ?', 'O stress ou a ansiedade pode influenciar ambos por nestas situações há diminuição da produção de oxitocina, que é a hormona do amor.', 'How can stress or anxiety can influence sexual desire and/or the affections in a loving relationship ?', 'Stress or anxiety can influence both because in these situations there is a decrease in the production of oxytocin, which is the hormone of love.', 'Mental Health'),
        (1, 'De que forma os afetos recebidos no seio familiar influenciam a forma como vivemos e expressamos a nossa sexualidade ?', 'A relação influencia da situação que vimos em casa, o ambiente familiar, o que afeta o que demonstramos com o nosso companheiro(a). Por exemplo, caso um filho tenha apenas uma mãe, não sabe o que deve dar à namorada.', 'How the affections received in the family influence the way in which live and express our sexuality ?', 'The relationship influences the situation we saw at home, the family environment, which affects what we demonstrate with our colleagues. For example, if a child has only one mother, he does not know what to give his girlfriend.', 'Mental Health'),
        (1, 'Que estratégias serão eficazes para prevenir o consumo de tabaco, sob várias formas entre os jovens ?', 'O mais importante é não começar, nem experimentar. Temos de aprender de dizer que não, não afetar com o ambiente familiar. Evitar ambiente onde há consumos de tabaco, ter muitas atividades (estar ocupado): jogar basquetebol, futebol, atividades extracurriculares, etc...', 'What strategies will be effective to prevent tobacco consumption, under various forms among the young ?', 'The most important thing is not to start, nor to experiment. We must learn to say no, not to affect with the family environment. Avoid environments where there is tobacco consumption, have many activities (be busy): play basketball, football, extracurricular activities, etc...', 'Prevention'),
        (1, 'Que estratégias serão eficazes para prevenir o consumo de álcool pelos jovens ?', 'Evitar ambiente onde há consumos de álcool, e preferir sempre a água, em ambientes de festas preferir bebidas sem álcool, ter muitas atividades (estar ocupado): jogar basquetebol, futebol, atividades extracurriculares, etc...', 'What strategies will be effective to prevent alcohol consumption by young people ?', 'Avoid environments where there is alcohol consumption, and always prefer water, in party settings prefer non-alcoholic drinks, have many activities (be busy): play basketball, football, extracurricular activities, etc...', 'Prevention'),
        (1, 'Que estratégias serão eficazes para prevenir o consumo de substâncias psicoativas pelos jovens ?', 'Evitar ambiente onde há consumos de substâncias psicoativas, evitar pessoas que vendem as substâncias e ter muitas atividades (estar ocupado): jogar basquetebol, futebol, atividades extracurriculares, etc...', 'What strategies will be effective in preventing substance use psychoactive by young people ?', 'Avoid environments where there is consumption of psychoactive substances, avoid people who sell the substances and have many activities (being busy): playing basketball, football, extracurricular activities, etc...', 'Prevention')
    ''')
    conn.commit()
    conn.close()

    cursor.execute('''
        INSERT INTO questions (id_group, pergunta, resposta, question, answer, category) VALUES
        (2, 'Qual a percentagem de jovens com doenças pulmonares por causa do tabaco ou com doenças relacionadas devido ao consumo de substâncias aditivas ?', 'Cerca de 16% dos jovens têm doenças pulmonares por causa do tabaco, e 10 em cada 100 desenvolvem problemas graves, como cancro no pulmão, devido ao consumo de substâncias aditivas.', 'What is the percentage of young people with lung diseases because of tobacco or with related diseases due to the consumption of addictive substances ?', 'About 16% of young people have lung diseases because of tobacco, and 10 in every 100 develop serious problems, such as lung cancer, due to the consumption of addictive substances.', 'Prevention'),
        (2, 'Qual a média de idade das pessoas que chegam com doenças relacionadas com o vício de bebidas alcoólicas ?', 'Quando o consumo de álcool é elevado e prolongado, os problemas de saúde costumam começar a aparecer por volta dos 40 anos.', 'What is the average age of people arriving with diseases related to addiction to alcoholic beverages ?', 'When alcohol consumption is high and prolonged, health problems usually start to appear around the age of 40.', 'Prevention'),
        (2, 'Quais são as maiores consequências para a sociedade (impacto social) desses comportamentos de dependências do tabaco, álcool e substâncias aditivas ?', 'Estas dependências acabam por aumentar doenças graves e criar problemas sociais como violência, acidentes e famílias desestruturadas.', 'What are the greatest consequences for society (social impact) of these behaviors of tobacco, alcohol and addictive substance dependencies ?', 'These dependencies end up increasing serious diseases and creating social problems such as violence, accidents, and broken families.', 'Prevention'),
        (2, 'Quais são as doenças mais frequentes relacionadas com substâncias aditivas ?', 'Pode causar cancro (principalmente no pulmão), doenças do fígado, problemas cardíacos, doenças respiratórias e também problemas mentais, como depressão e ansiedade.', 'What are the most frequent diseases related to addictive substances ?', 'It can cause cancer (mainly in the lungs), liver diseases, heart problems, respiratory diseases, and also mental problems such as depression and anxiety.', 'Prevention'),
        (2, 'Quais são os riscos e efeitos a curto prazo do consumo de tabaco e substâncias aditivas ?', 'O consumo pode causar problemas imediatos como cansaço, dificuldade em respirar e alterações no humor. Além disso, podem afetar o pulmão e o cérebro em desenvolvimento. Nos jovens, o risco é normalizar o vício, abrindo portas para problemas maiores no futuro.', 'What are the short-term risks and effects of tobacco and addictive substance consumption ?', 'Consumption can cause immediate problems such as fatigue, difficulty breathing, and mood swings. In addition, they can affect the lungs and the developing brain. In young people, the risk is normalizing the addiction, opening doors to bigger problems in the future.', 'Prevention'),
        (2, 'Os cigarros eletrónicos, como iqos e vapes, são menos prejudiciais para o ser humano em comparação com o cigarro normal ?', 'Ainda não se sabe completamente como os iqos e vapes atuam no corpo humano, por serem relativamente recentes. Os efeitos a longo prazo ainda não são totalmente conhecidos, mas já existem casos de problemas graves.', 'Are electronic cigarettes, such as iqos and vapes, less harmful to humans compared to regular cigarettes ?', 'It is not yet fully known how iqos and vapes act on the human body, as they are relatively recent. The long-term effects are not yet fully known, but there are already cases of serious problems.', 'Prevention'),
        (2, 'Quais os sintomas da infecção pulmonar provocada pelo tabaco ?', 'Os sintomas incluem muita tosse, febre e mal-estar, pois o pulmão fica mais vulnerável a infeções.', 'What are the symptoms of lung infection caused by tobacco ?', 'Symptoms include a lot of coughing, fever, and malaise, as the lung becomes more vulnerable to infections.', 'Prevention'),
        (2, 'Quais são os impactos prejudiciais para o indivíduo do consumo exagerado de bebidas alcoólicas ?', 'O álcool afeta o fígado e o cérebro, prejudica o raciocínio e pode causar dependência, tornando difícil parar.', 'What are the harmful impacts for the individual of excessive consumption of alcoholic beverages ?', 'Alcohol affects the liver and the brain, impairs reasoning, and can cause dependence, making it difficult to stop.', 'Prevention'),
        (2, 'Quais são os conselhos para deixar os vícios do consumo de tabaco ?', 'O melhor conselho é nunca começar.', 'What is the advice for quitting tobacco addictions ?', 'The best advice is never to start.', 'Prevention'),
        (2, 'Pode-se ter uma vida normal com o consumo moderado de substâncias psicoativas ?', 'Mesmo em pouca quantidade, existe sempre o risco de desenvolver problemas de saúde no futuro.', 'Can one have a normal life with moderate consumption of psychoactive substances ?', 'Even in small amounts, there is always a risk of developing health problems in the future.', 'Prevention'),
        (2, 'Quantas bebidas alcoólicas por semana são consideradas seguras para uma mulher e para um homem ?', 'Atualmente, a recomendação mais segura é não consumir álcool.', 'How many alcoholic drinks per week are considered safe for a woman and a man ?', 'Currently, the safest recommendation is not to consume alcohol.', 'Prevention'),
        (2, 'O que é ressaca? Como evitar e como resolver ?', 'A ressaca acontece devido à desidratação do corpo. Para aliviar, deve-se beber muita água. A forma mais eficaz de evitar é não consumir álcool.', 'What is a hangover? How to avoid it and how to solve it ?', 'A hangover happens due to the body\'s dehydration. To alleviate it, one should drink plenty of water. The most effective way to avoid it is not to consume alcohol.', 'Prevention')
    ''')

    conn.commit()
    conn.close()

    cursor.execute('''
        INSERT INTO questions (id_group, pergunta, resposta, question, answer, category) VALUES
        (3, 'Porque é que os casos de transmissão de doenças sexualmente transmissíveis têm aumentado em adolescentes?', 'As DST são mais frequentes em adolescentes porque o corpo ainda está em desenvolvimento e é mais vulnerável do que o de um adulto.', 'Why have cases of sexually transmitted diseases increased among teenagers?', 'STIs are more common in teenagers because their bodies are still developing and are more vulnerable than an adults.', 'Prevention'),
        (3, 'Podemos apanhar uma doença sexualmente transmissível na primeira relação?', 'Sim, é possível contrair uma DST na primeira relação sexual, pois a transmissão depende do contacto com uma pessoa infetada, não do número de relações.', 'Can we contract a sexually transmitted disease during our first sexual encounter?', 'Yes, it is possible to contract an STI during the first sexual encounter, as transmission depends on contact with an infected person, not the number of encounters.', 'Prevention'),
        (3, 'Podemos ter uma doença sexualmente transmissível sem ter sintomas?', 'Sim, é possível ter DST sem sintomas, o que é comum em adolescentes e adultos jovens. Algumas DST frequentemente assintomáticas são clamídia, gonorreia, HPV, HIV (fase inicial) e sífilis.', 'Can we have a sexually transmitted disease without experiencing symptoms?', 'Yes, it is possible to have an STI without symptoms, which is common in teenagers and young adults. Some frequently asymptomatic STIs are chlamydia, gonorrhea, HPV, HIV (early stage), and syphilis.', 'Prevention'),
        (3, 'Como podemos evitar o mau odor vaginal?', 'O odor vaginal pode ser normal e geralmente está ligado a alterações do pH ou infeções. Deve-se lavar apenas a parte externa da vulva com água e sabonete íntimo suave, evitando duches vaginais.', 'How can we prevent vaginal odor?', 'Vaginal odor can be normal and is usually linked to pH changes or infections. Only the external part of the vulva should be washed with water and mild intimate soap, avoiding vaginal douches.', 'Prevention'),
        (3, 'É normal ter dores menstruais intensas?', 'Dores menstruais são comuns, sobretudo na adolescência. Podem ser aliviadas com bolsa de água quente, exercício e medicação.', 'Is it normal to have intense menstrual cramps?', 'Menstrual cramps are common, especially in adolescence. They can be relieved with a hot water bottle, exercise, and medication.', 'Prevention'),
        (3, 'Andar sempre cansado, mesmo dormindo bem, pode estar ligado a questões emocionais?', 'Sim, pode estar relacionado. Mesmo dormindo o suficiente, a qualidade do sono pode ser afetada por questões emocionais.', 'Could being constantly tired, even after sleeping well, be linked to emotional issues?', 'Yes, it can be related. Even with sufficient sleep, sleep quality can be affected by emotional issues.', 'Prevention'),
        (3, 'Pensar demais e não conseguir “desligar” a cabeça será sintoma de ansiedade ou só excesso de preocupações?', 'Pensar demais é comum, mas quando é frequente, difícil de controlar e interfere no bem-estar, pode ser um sintoma de ansiedade.', 'Is overthinking and not being able to "switch off" a symptom of anxiety or just excessive worrying?', 'Overthinking is common, but when it is frequent, difficult to control, and interferes with well-being, it can be a symptom of anxiety.', 'Prevention'),
        (3, 'Mudanças repentinas de humor são normais ou já justificam acompanhamento médico?', 'Mudanças de humor ocasionais são normais, mas quando são repentinas, frequentes ou intensas, podem indicar um problema.', 'Are sudden mood swings normal or do they justify medical attention?', 'Occasional mood swings are normal, but when they are sudden, frequent, or intense, they may indicate a problem.', 'Prevention'),
        (3, 'Guardarmos tudo para nós em vez de falarmos com alguém pode afetar o corpo e a mente?', 'Guardar emoções aumenta o stress e a ansiedade, prejudicando o sono, a concentração e o humor. Falar com alguém ou procurar ajuda profissional protege a saúde.', 'Can keeping everything to ourselves instead of talking to someone affect our body and mind?', 'Holding in emotions increases stress and anxiety, harming sleep, concentration, and mood. Talking to someone or seeking professional help protects health.', 'Prevention'),
        (3, 'A dificuldade em dizer não aos outros pode prejudicar a nossa saúde?', 'A dificuldade em dizer “não” pode causar stress, frustração e esgotamento. Estabelecer limites é essencial para o equilíbrio.', 'Can difficulty saying no to others harm our health?', 'Difficulty saying "no" can cause stress, frustration, and exhaustion. Setting boundaries is essential for balance.', 'Prevention'),
        (3, 'Sentirmo-nos sozinhos mesmo rodeados de pessoas é normal?', 'Sentir-se sozinho mesmo acompanhado é comum, mas quando é frequente pode indicar dificuldades e deve ser valorizado, procurando apoio se necessário.', 'Is it normal to feel lonely even when surrounded by people?', 'Feeling lonely even when accompanied is common, but when frequent it can indicate difficulties and should be taken seriously, seeking support if necessary.', 'Prevention'),
        (3, 'Relações afetivas tóxicas podem causar sintomas físicos reais?', 'Relações tóxicas podem causar sintomas físicos como insónia, dores de cabeça e problemas digestivos, além de aumentar o risco de ansiedade, depressão e doenças cardiovasculares, devido ao stress crónico.', 'Can toxic romantic relationships cause real physical symptoms?', 'Toxic relationships can cause physical symptoms such as insomnia, headaches, and digestive problems, as well as increase the risk of anxiety, depression, and cardiovascular disease due to chronic stress.', 'Prevention');
                   ''')