import sqlite3

conn = sqlite3.connect('FAQHealth.db')
cursor = conn.cursor()

def create_tables():
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS groups (
        id_group INT PRIMARY KEY AUTOINCREMENT,
        name TEXT NOT NULL,
        grade TEXT DEFAULT NULL);''')
    
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS questions (
        id_question TINYINT PRIMARY KEY AUTOINCREMENT,
        id_group TINYINT,
        question TEXT NOT NULL,
        answer TEXT NOT NULL,
        pergunta TEXT NOT NULL,
        resposta TEXT NOT NULL,
        votes TINYINT DEFAULT 0,
        category TEXT DEFAULT NULL,
        FOREIGN KEY (id_group) REFERENCES groups(id_group));''')
    conn.commit()
    conn.close()

def insert_group():
    cursor.execute('''
        INSERT INTO groups (name, grade) VALUES
        ('Tomás Castelo, Vasco Machado, Samuel Rodrigues, Walter João e Waldir Milagre ', '2ºJ'),
        ('Ânia, Marta e Tomé', NULL),
        ('Taissa e Esperança', '3ºJ'),
        ('Pedro Lopes e Orlean Mpaka', '2ºL'),
        ('Isaac, Lara, Beatriz e Madalena', NULL),
        ('Diogo , Filipe, Rodrigo e Simão', NULL),
        ('Luana Santos e Rodrigo Silva', NULL),
        ('Maria Meireles, Diego Pernia, Rodrigo Fernandes e Filipa Cruz', '2ºL');''')
    conn.commit()
    conn.close()

def insert_questions():
    cursor.execute('''
        INSERT INTO questions (id_group, pergunta, resposta, question, answer, category) VALUES
        (1, 'Quantas horas deve dormir um jovem, por noite, para ter um sono adequado ?', 'Um sono arqueado depende muito do jovem em si, idealmente no mínimo 7-8 horas. Os atletas precisam dormir mais de 7-8 horas.', 'How many hours should a young person sleep, each night, to have adequate sleep ?', 'An acurate sleep depends very much on the young person himself, ideally at least 7-8 hours. Athletes need to sleep more than 7-8 hours.', 'Mental Health'),
        (1, 'O que fazer para ter mais ânimo a fazer exercício físico ?', 'Várias maneiras: encontrar uma coisa que goste, arranjar companhia, e tentar incluir pequenas atividades no dia a dia, por exemplo, ir a pé invés de andar de autocarro ou subir as escoados invés de andar de elevador.', 'What to do if we want to have more encouragement to exercise physically ?', 'Several ways: find something you like, get company, and try to include small activities in your daily life, for example, walking instead of taking the bus or climbing the stairs instead of taking the elevator.', 'Training'),
        (1, 'Que sinais indicam que alguém está ansioso ?', 'A ansiedade varia de pessoa a pessoa, as indicações que uma pessoa está a sofrer ansiedade são: sua mais, batimento cardíaco mais rápido, treme mais frequentemente, tem dificuldade a dormir, pode vomitar ou estar nauseado, pode falar muito. Mas a ansiedade tem pontos positivos, porque deixa os humanos alertados, mas caso a ansiedade seja em excesso pode afetar no dia a dia.', 'What signs indicate that someone is anxious ?', 'Anxiety varies from person to person, the indications that a person is experiencing anxiety are: more perspiration, the heartbeat is faster, more frequent tremors, difficulty sleeping, maybe vomit or nausea, excessive talking. But anxiety has positive points, because it alerts humans, but if anxiety is too much it can affect everyday life.', 'Mental Health'),
        (1, 'Qual impacto que o uso excessivo do telemóvel, do computador ou televisão têm na qualidade do meu sono ?', 'Os eletrônicos têm luzes azuis, dá indicação ao cérebro que é hora de acordar e não dormir e isso causa a produção de melatonina. A melatonina é a responsável pela regulação do sono.', 'What impact does the excessive use of the mobile phone, computer or television have on my sleep quality ?', 'Electronics have blue lights that give the brain indication that it is time to wake up and not sleep and this causes the production of melatonin. Melatonin is responsible for regulating sleep.', 'Mental Health'),
        (1, 'De que forma o consumo de cafeína pode afetar a qualidade do meu sono ?', 'O consumo de cafeína impede ao cérebro que não estamos cansados, o que impede de dormirmos, o que pode causar insónias, afeta a qualidade de sono da seguinte forma: demoramos mais a adormecer.', 'How can caffeine consumption affect the quality of my sleep ?', 'Caffeine consumption prevents the brain from being tired, which prevents us from sleeping, which can cause insomnia, affects sleep quality in the following way: we take longer to fall asleep.', 'Mental Health'),
        (1, 'Que medidas os jovens podem adotar para melhorar o descanso e conseguir um sono mais profundo ?', 'Para tornar um sono mais profundo devemos acordar e deitar à mesma hora, rotina antes de ir dormir, evitar o uso de ecrãs 30 minutos antes de dormir, refeições leves ao jantar e não beber cafeína 8 horas antes de dormir, os quartos tem de estar entre os 18º e os 21º graus, o quarto deve estar o mais escuro possível.', 'What measures can young people adopt to improve rest and achieve a deeper sleep ?', 'To make a deeper sleep, we must wake up and go to bed at the same time, have a routine before going to sleep, avoid using screens 30 minutes before sleeping, light meals at dinner and do not drink caffeine 8 hours before bedtime; rooms must be between 18° and 21° degrees, the room should be as dark as possible.', 'Mental Health'),
        (1, 'O que fazer quando existe dificuldade em adormecer apesar de se estar cansado ?', 'Temos de levantar, ir à casa de banho, comer alguma coisa ou beber alguma coisa leve e antes de deitar escrever num papel o que mais preocupa, e depois podemos deitar-nos.', 'What to do when there is difficulty falling asleep despite being tired ?', 'We have to get up, go to the bathroom, eat something or drink something light and before lying down write on a piece of paper what worries us most, and then we can go to bed.', 'Mental Health'),
        (1, 'De que forma é que a utilização de produtos de limpeza muito agressivos (com pH elevado ou tensioativos fortes) pode comprometer a função da barreira da pele ? E quais são os sinais de alerta ?', 'Caso usemos produtos fortes, a pele fica seca, abrindo feridas. sinais: pele vermelha, inchada, dorida, com pus, ou com comichão.', 'How is the use of very aggressive cleaning products (with high pH or strong surfactants) may compromise the function of skin barrier ? And what are the warning signs ?', 'If we use strong products, the skin becomes dry, opening wounds. signs: red skin, swollen, sore, with pus, or itchy.', 'Prevention'),
        (1, 'De que forma o stress ou a ansiedade podem influenciar o desejo sexual e/ou os afetos numa relação amorosa ?', 'O stress ou a ansiedade pode influenciar ambos por nestas situações há diminuição da produção de oxitocina, que é a hormona do amor.', 'How can stress or anxiety can influence sexual desire and/or the affections in a loving relationship ?', 'Stress or anxiety can influence both because in these situations there is a decrease in the production of oxytocin, which is the hormone of love.', 'Mental Health'),
        (1, 'De que forma os afetos recebidos no seio familiar influenciam a forma como vivemos e expressamos a nossa sexualidade ?', 'A relação influencia da situação que vimos em casa, o ambiente familiar, o que afeta o que demonstramos com o nosso companheiro(a). Por exemplo, caso um filho tenha apenas uma mãe, não sabe o que deve dar à namorada.', 'How the affections received in the family influence the way in which live and express our sexuality ?', 'The relationship influences the situation we saw at home, the family environment, which affects what we demonstrate with our colleagues. For example, if a child has only one mother, he does not know what to give his girlfriend.', 'Mental Health'),
        (1, 'Que estratégias serão eficazes para prevenir o consumo de tabaco, sob várias formas entre os jovens ?', 'O mais importante é não começar, nem experimentar. Temos de aprender de dizer que não, não afetar com o ambiente familiar. Evitar ambiente onde há consumos de tabaco, ter muitas atividades (estar ocupado): jogar basquetebol, futebol, atividades extracurriculares, etc...', 'What strategies will be effective to prevent tobacco consumption, under various forms among the young ?', 'The most important thing is not to start, nor to experiment. We must learn to say no, not to affect with the family environment. Avoid environments where there is tobacco consumption, have many activities (be busy): play basketball, football, extracurricular activities, etc...', 'Prevention'),
        (1, 'Que estratégias serão eficazes para prevenir o consumo de álcool pelos jovens ?', 'Evitar ambiente onde há consumos de álcool, e preferir sempre a água, em ambientes de festas preferir bebidas sem álcool, ter muitas atividades (estar ocupado): jogar basquetebol, futebol, atividades extracurriculares, etc...', 'What strategies will be effective to prevent alcohol consumption by young people ?', 'Avoid environments where there is alcohol consumption, and always prefer water, in party settings prefer non-alcoholic drinks, have many activities (be busy): play basketball, football, extracurricular activities, etc...', 'Prevention'),
        (1, 'Que estratégias serão eficazes para prevenir o consumo de substâncias psicoativas pelos jovens ?', 'Evitar ambiente onde há consumos de substâncias psicoativas, evitar pessoas que vendem as substâncias e ter muitas atividades (estar ocupado): jogar basquetebol, futebol, atividades extracurriculares, etc...', 'What strategies will be effective in preventing substance use psychoactive by young people ?', 'Avoid environments where there is consumption of psychoactive substances, avoid people who sell the substances and have many activities (being busy): playing basketball, football, extracurricular activities, etc...', 'Prevention')
    ''')
    conn.commit()
    conn.close()

    cursor.execute('''
    INSERT INTO questions (id_group, pergunta, resposta, question, answer, category) VALUES
    (2, 'Como podemos melhorar a nossa imunidade no dia a dia ?', 'Podemos melhorar a nossa imunidade com uma alimentação equilibrada, prática regular de exercício físico, sono adequado e uma boa hidratação.', 'How can we improve our immunity in everyday life ?', 'We can improve our immunity with a balanced diet, regular physical exercise, adequate sleep, and good hydration.', 'prevention'),
    (2, 'Quantas horas de sono são recomendadas para um jovem ?', 'Um jovem deve dormir, em média, entre 8 a 10 horas por noite.', 'How many hours of sleep are recommended for a young person ?', 'A young person should sleep, on average, between 8 and 10 hours per night.', 'prevention'),
    (2, 'Com que frequência um jovem deve praticar exercício físico ?', 'Recomenda-se pelo menos 3 a 5 vezes por semana, mínimo de 30 minutos.', 'How often should a young person practice physical exercise ?', 'It is recommended to exercise at least 3 to 5 times a week, for a minimum of 30 minutes.', 'training'),
    (2, 'Com que frequência devemos realizar consultas de rotina no dentista/higienista ?', 'As consultas devem ser feitas de 6 em 6 meses, salvo indicação diferente dadas pelo médico.', 'How often should we have routine check-ups with the dentist/dental hygienist ?', 'Check-ups should be done every 6 months, unless otherwise advised by the doctor.', 'prevention'),
    (2, 'Como podemos evitar as doenças sexualmente transmissíveis ?', 'Usar sempre preservativo, fazendo testes regulares e evitando comportamentos de risco.', 'How can we prevent sexually transmitted diseases ?', 'Always use condoms, have regular testing, and avoid risky behaviors.', 'prevention'),
    (2, 'Qual é a importância da prática de desporto regular para a nossa saúde física e mental ?', 'A prática de desporto melhora a condição física, fortalece o nosso sistema imunitário, reduz o stress e melhora o bem-estar mental pois libertamos hormonas.', 'What is the importance of regular sports practice for our physical and mental health ?', 'Practicing sports improves physical condition, strengthens our immune system, reduces stress, and improves mental well-being because we release hormones.', 'training'),
    (2, 'De que forma uma alimentação equilibrada pode melhorar rendimento durante a prática desportiva ?', 'Fornece energia, melhora a recuperação muscular e ajuda na concentração e resistência, durante a prática de desporto o nosso corpo transforma o que comemos em energia.', 'How can a balanced diet improve performance during sports practice ?', 'It provides energy, improves muscle recovery, and helps with concentration and endurance; during sports practice, our body turns what we eat into energy.', 'nutrition'),
    (2, 'Quais são os métodos contracetivos mais indicados para uma jovem ?', 'Preservativo e pílula para pessoas responsáveis, se a pessoa for esquecida é recomendado por o implanon.', 'Which contraceptive methods are most suitable for a young woman ?', 'Condoms and the pill are recommended for responsible people, if someone is forgetful the implanon is recommended.', 'prevention'),
    (2, 'Quais são os efeitos no nosso organismo do consumo de tabaco e substâncias aditivas ?', 'Podem causar dependência, problemas respiratórios, cardiovasculares e danos na saúde mental.', 'What are the effects of tobacco and addictive substances on our body ?', 'They can cause addiction, respiratory and cardiovascular problems, and damage mental health.', 'prevention'),
    (2, 'O que podemos fazer para aliviar cólicas e desconfortos durante a menstruação ?', 'Usar compressas quentes, manter boa hidratação , massagens adequadas, tomar medicação recomendada e de corpo para corpo a reação é diferente e a dor também.', 'What can we do to relieve cramps and discomfort during menstruation ?', 'Use warm compresses, stay well hydrated, do appropriate massages, take recommended medication, and remember that reactions and pain vary from body to body.', 'prevention'),
    (2, 'Por que motivo, nós jovens, temos tantas cólicas menstruais ?', 'Desregulação hormonal, falta de práticas contraceptivas que ajudam a regular o período menstrual.', 'Why do we, as young women, have so many menstrual cramps ?', 'Hormonal imbalance and lack of contraceptive practices that help regulate the menstrual cycle.', 'prevention'),
    (2, 'Como funciona o nosso ciclo menstrual ?', 'É o ciclo hormonal mensal que prepara o corpo para uma possível gravidez, dura cerca de 28 dias.', 'How does our menstrual cycle work ?', 'It is the monthly hormonal cycle that prepares the body for a possible pregnancy and lasts about 28 days.', 'prevention'),
    (2, 'Devemos fazer higiene oral profissional regularmente ?', 'O recomendado é de 6 em 6 meses, dependendo da saúde oral de cada pessoa.', 'Should we have professional oral hygiene regularly ?', 'It is recommended every 6 months, depending on each person’s oral health.', 'prevention'),
    (2, 'Com que frequência devemos ir ao ginecologista, sendo jovens ?', 'Só é necessário se o médico de família recomendar ou não dependendo do caso.', 'How often should young women visit a gynecologist ?', 'It depends on the case and on whether the family doctor recommends it.', 'prevention'),
    (2, 'É normal termos dores durante a menstruação situadas em sítios diferentes no corpo ?', 'Sim, as dores podem localizar-se noutros sítios do corpo dependendo de pessoa para pessoa.', 'Is it normal to have pain during menstruation in different parts of the body ?', 'Yes, pain can be felt in other parts of the body and varies from person to person.', 'prevention')
''')
    
    conn.commit()
    conn.close()

    cursor.execute('''
        INSERT INTO questions (id_group, pergunta, resposta, question, answer, category) VALUES
        (3, 'Porque é que os casos de transmissão de doenças sexualmente transmissíveis têm aumentado em adolescentes ?', 'As DST são mais frequentes em adolescentes porque o corpo ainda está em desenvolvimento e é mais vulnerável do que o de um adulto.', 'Why have cases of sexually transmitted diseases increased among teenagers ?', 'STIs are more common in teenagers because their bodies are still developing and are more vulnerable than an adults.', 'Prevention'),
        (3, 'Podemos apanhar uma doença sexualmente transmissível na primeira relação ?', 'Sim, é possível contrair uma DST na primeira relação sexual, pois a transmissão depende do contacto com uma pessoa infetada, não do número de relações.', 'Can we contract a sexually transmitted disease during our first sexual encounter ?', 'Yes, it is possible to contract an STI during the first sexual encounter, as transmission depends on contact with an infected person, not the number of encounters.', 'Prevention'),
        (3, 'Podemos ter uma doença sexualmente transmissível sem ter sintomas ?', 'Sim, é possível ter DST sem sintomas, o que é comum em adolescentes e adultos jovens. Algumas DST frequentemente assintomáticas são clamídia, gonorreia, HPV, HIV (fase inicial) e sífilis.', 'Can we have a sexually transmitted disease without experiencing symptoms ?', 'Yes, it is possible to have an STI without symptoms, which is common in teenagers and young adults. Some frequently asymptomatic STIs are chlamydia, gonorrhea, HPV, HIV (early stage), and syphilis.', 'Prevention'),
        (3, 'Como podemos evitar o mau odor vaginal ?', 'O odor vaginal pode ser normal e geralmente está ligado a alterações do pH ou infeções. Deve-se lavar apenas a parte externa da vulva com água e sabonete íntimo suave, evitando duches vaginais.', 'How can we prevent vaginal odor ?', 'Vaginal odor can be normal and is usually linked to pH changes or infections. Only the external part of the vulva should be washed with water and mild intimate soap, avoiding vaginal douches.', 'Prevention'),
        (3, 'É normal ter dores menstruais intensas ?', 'Dores menstruais são comuns, sobretudo na adolescência. Podem ser aliviadas com bolsa de água quente, exercício e medicação.', 'Is it normal to have intense menstrual cramps?', 'Menstrual cramps are common, especially in adolescence. They can be relieved with a hot water bottle, exercise, and medication.', 'Prevention'),
        (3, 'Andar sempre cansado, mesmo dormindo bem, pode estar ligado a questões emocionais ?', 'Sim, pode estar relacionado. Mesmo dormindo o suficiente, a qualidade do sono pode ser afetada por questões emocionais.', 'Could being constantly tired, even after sleeping well, be linked to emotional issues ?', 'Yes, it can be related. Even with sufficient sleep, sleep quality can be affected by emotional issues.', 'Prevention'),
        (3, 'Pensar demais e não conseguir “desligar” a cabeça será sintoma de ansiedade ou só excesso de preocupações?', 'Pensar demais é comum, mas quando é frequente, difícil de controlar e interfere no bem-estar, pode ser um sintoma de ansiedade.', 'Is overthinking and not being able to "switch off" a symptom of anxiety or just excessive worrying ?', 'Overthinking is common, but when it is frequent, difficult to control, and interferes with well-being, it can be a symptom of anxiety.', 'Prevention'),
        (3, 'Mudanças repentinas de humor são normais ou já justificam acompanhamento médico ?', 'Mudanças de humor ocasionais são normais, mas quando são repentinas, frequentes ou intensas, podem indicar um problema.', 'Are sudden mood swings normal or do they justify medical attention ?', 'Occasional mood swings are normal, but when they are sudden, frequent, or intense, they may indicate a problem.', 'Prevention'),
        (3, 'Guardarmos tudo para nós em vez de falarmos com alguém pode afetar o corpo e a mente ?', 'Guardar emoções aumenta o stress e a ansiedade, prejudicando o sono, a concentração e o humor. Falar com alguém ou procurar ajuda profissional protege a saúde.', 'Can keeping everything to ourselves instead of talking to someone affect our body and mind?', 'Holding in emotions increases stress and anxiety, harming sleep, concentration, and mood. Talking to someone or seeking professional help protects health.', 'Prevention'),
        (3, 'A dificuldade em dizer não aos outros pode prejudicar a nossa saúde ?', 'A dificuldade em dizer “não” pode causar stress, frustração e esgotamento. Estabelecer limites é essencial para o equilíbrio.', 'Can difficulty saying no to others harm our health?', 'Difficulty saying "no" can cause stress, frustration, and exhaustion. Setting boundaries is essential for balance.', 'Prevention'),
        (3, 'Sentirmo-nos sozinhos mesmo rodeados de pessoas é normal ?', 'Sentir-se sozinho mesmo acompanhado é comum, mas quando é frequente pode indicar dificuldades e deve ser valorizado, procurando apoio se necessário.', 'Is it normal to feel lonely even when surrounded by people ?', 'Feeling lonely even when accompanied is common, but when frequent it can indicate difficulties and should be taken seriously, seeking support if necessary.', 'Prevention'),
        (3, 'Relações afetivas tóxicas podem causar sintomas físicos reais ?', 'Relações tóxicas podem causar sintomas físicos como insónia, dores de cabeça e problemas digestivos, além de aumentar o risco de ansiedade, depressão e doenças cardiovasculares, devido ao stress crónico.', 'Can toxic romantic relationships cause real physical symptoms ?', 'Toxic relationships can cause physical symptoms such as insomnia, headaches, and digestive problems, as well as increase the risk of anxiety, depression, and cardiovascular disease due to chronic stress.', 'Prevention');
                   ''')

    conn.commit()
    conn.close()

    cursor.execute('''
        INSERT INTO questions (id_group, pergunta, resposta, question, answer, category) VALUES
        (4, 'O que podes fazer no dia a dia para melhorar a tua saúde mental ?', 'Afastar-nos de conflitos, ter uma boa rede de apoio (amigos e familiares), uma alimentação saudável e o exercício físico.', 'What can you do in your daily life to improve your mental health ?', 'Staying away from conflicts, having a good support network (friends and family), eating a healthy diet, and exercising.', 'mental health'),
        (4, 'Como é que pedes ajuda quando te sentes sobrecarregado emocionalmente ?', 'procurar ajuda a pessoas mais próximas e, se nao tiver resposta, a assistências de saúde', 'How do you ask for help when you feel emotionally overwhelmed ?', 'Seeking help from people close to you and, if you don’t get support, turning to healthcare professionals.', 'mental health'),
        (4, 'Que estratégias podem ajudar a lidar com a ansiedade escolar ?', 'distrair me para nao desgastar me e pensar sempre no mesmo', 'What strategies can help deal with school-related anxiety ?', 'Distracting yourself so you don’t exhaust yourself by constantly thinking about the same thing.', 'mental health'),
        (4, 'O que significa ter competências socioemocionais bem desenvolvidas ?', 'sentires te bem, nao importar tanto com oq acontece a minha volta, lidar bem com críticas e pressões, ter um bom grupo de amigos', 'What does it mean to have well-developed socio-emotional skills ?', 'Feeling good about yourself, not worrying too much about what happens around you, handling criticism and pressure well, and having a good group of friends.', 'mental health'),
        (4, 'O que é essencial para manter uma relação afetiva saudável ?', 'respeito, gostar um do outro, ter os mesmos padroes de futuro', 'What is essential to maintain a healthy romantic relationship ?', 'Respect, caring about each other, and having similar future goals.', 'mental health'),
        (4, 'Como podes comunicar limites pessoais de forma clara e respeitosa ?', 'falar e muito importante, meter limites para nao acontecer nada de mal e saber concordar os dois sobre um certo assunto', 'How can you communicate personal boundaries clearly and respectfully ?', 'Talking is very important, setting boundaries to prevent anything bad from happening, and making sure both people agree on certain matters.', 'mental health'),
        (4, 'Por que razão é importante obter informação fiável sobre sexualidade ?', 'por varios motivos, temos que ter noção dos benefícios e perigos (gravidez, infeções)', 'Why is it important to obtain reliable information about sexuality ?', 'For several reasons; we need to be aware of the benefits and risks (pregnancy, infections).', 'prevention'),
        (4, 'O que deve incluir uma refeição equilibrada ?', 'metade do prato legumes (cosas verdes), porção de hidratos de carbono (batata, cenoura) e o resto carne peixe. Evitar gorduras, refrigerantes, bolos, etc', 'What should a balanced meal include ?', 'Half of the plate should be vegetables (especially greens), a portion of carbohydrates (potatoes, carrots), and the rest meat or fish. Avoid fats, soft drinks, cakes, etc.', 'nutrition'),
        (4, 'Como podes organizar a tua rotina para seres mais ativo fisicamente ?', 'ter um padrão diario e ver o nosso horário, ter um tempinho por dia ( 3 4 dias por semana), depois das aulas ou do trabalho ter um trmoo para exercício e depois focar me nos restantes problemas', 'How can you organize your routine to be more physically active ?', 'Having a daily routine and checking your schedule, setting aside some time each day (3–4 days a week), exercising after school or work, and then focusing on other responsibilities.', 'training'),
        (4, 'Quais são os benefícios de praticar exercício físico regularmente ?', 'benefícios em tudo, parte mental, evita doenças do coração e do cerebro, lezoes, evita depressões', 'What are the benefits of exercising regularly ?', 'Benefits in every aspect: mental health, preventing heart and brain diseases, injuries, and depression.', 'training'),
        (4, 'De que forma a alimentação influencia o teu desempenho escolar ?', 'influência na qualidade cerebral e também nos problemas de saúde, e na qualidade social (bullying)', 'How does nutrition influence your school performance ?', 'It influences brain performance, overall health problems, and even social aspects (like bullying).', 'nutrition'),
        (4, 'Com que frequência se deve escovar os dentes e porquê ?', 'cada vez que comemos, no minimo 2 vezes ao dia, de manha e a noite para evitar problemas e caris', 'How often should you brush your teeth and why ?', 'Every time you eat, at least twice a day, in the morning and at night, to prevent problems and cavities.', 'prevention'),
        (4, 'Como a alimentação pode afetar a saúde dos teus dentes ?', 'tudo o que seja doces e açúcares, se nao for lavado depois pode causar caris, infecções, dentes podres, fazendo a higiene dental piorar', 'How can diet affect the health of your teeth ?', 'Sweets and sugars, if not cleaned properly, can cause cavities, infections, rotten teeth, and worsen oral hygiene.', 'nutrition'),
        (4, 'Que sinais indicam que precisas de uma consulta no dentista ?', 'dor de dentes, ver alguma parte do dente preta (caries) ou fazer consultas gerais antes de termos algo para tarmos prevenidos', 'What signs indicate that you need to see a dentist ?', 'Tooth pain, seeing a black spot on a tooth (cavity), or having regular check-ups to prevent problems before they start.', 'prevention'),
        (4, 'Quantas horas de sono são recomendadas para adolescentes ?', 'pelo menos 8 horas, ou 9-10 horas', 'How many many hours of sleep are recommended for teenagers ?', 'At least 8 hours, ideally 9–10 hours.', 'prevention')
        ''')

    conn.commit()
    conn.close()

    cursor.execute('''
        INSERT INTO questions (id_group, pergunta, resposta, question, answer, category) VALUES
        (5, 'Por quanto tempo devemos lavar os dentes ?', '60 a 90 seg', 'For how long should we brush our teeth ?', '60 to 90 seconds.', 'prevention'),
        (5, 'Como ajudar alguém com fobia social ?', 'Mostra disponibilidade, mas o certo é ter ajuda mais profissional', 'How can we help someone who has social phobia ?', 'Show availability and support, but professional help is the most appropriate approach.', 'mental health'),
        (5, 'Qual a melhor posição para dormir ?', 'Uma que na cause desconforto', 'What is the best sleeping position ?', 'A position that does not cause discomfort.', 'prevention'),
        (5, 'Em que situação devemos/podemos usar substancias aditivas (creatina,energético,cafeina) ?', 'A acordar de manha', 'In what situations should or can we use performance-enhancing or stimulating substances (such as creatine, energy drinks, or caffeine) ?', 'When waking up in the morning.', 'nutrition'),
        (5, 'Com que frequência devemos escovar os dentes ?', '2 vezes por dia', 'How often should we brush our teeth ?', 'Twice a day.', 'prevention'),
        (5, 'Quais são os sinais de que alguém está emocionalmente sobrecarregado ?', 'Ansiedade, perturbação do sono, afastamento social e menos rendimento', 'What are the signs that someone is emotionally overwhelmed ?', 'Anxiety, sleep disturbances, social withdrawal, and reduced performance.', 'mental health'),
        (5, 'O que é consentimento intimo , e como isso afeta um relacionamento ?', 'Consciência dos limites e respeito mutuo no relacionamento é a chave para evitar esse acontecimento', 'What is intimate consent, and how does it affect a relationship ?', 'Awareness of personal limits.', 'mental health'),
        (5, 'Como a dependência da nicotina se desenvolve ?', 'Com os fenómenos crescentes da dose resultando em doses de dependência', 'How does nicotine dependence develop ?', 'Through increasing dosage over time, which can lead to dependence.', 'prevention'),
        (5, 'com que frequência é recomendado manter a atividade física por semana ?', 'O ideal para tal seria até 5 vezes por semana mas claro que com as suas pausas para o corpo recuperar-se', 'How often is it recommended to engage in physical activity each week ?', 'Around five times per week.', 'training'),
        (5, 'Como ajudar alguém com fobia social a ser mais extrovertida ?', 'Ajuda profissional médica e ajuda dos amigos/familiares pois assim mostramos disponibilidade para a pessoa', 'How can we help someone with social phobia become more outgoing ?', 'Professional medical support, along with help from friends and family.', 'mental health'),
        (5, 'Quanto tempo devemos dormir ?', '7 a 8 Horas de sono', 'How many hours of sleep do we need ?', '7 to 8 hours of sleep.', 'prevention'),
        (5, 'Em que medida o tabagismo afeta a vida social de uma pessoa ?', 'Socialmente contem ajuda para o envolvimento social, porem sempre poderá prejudicar a vontade de estar ao pé das outras e o bem estar do próprio', 'To what extent does smoking affect a person’s social life ?', 'Socially, it may sometimes facilitate interaction, but when abused, it can reduce the desire to be around others.', 'prevention'),
        (5, 'procura de afeto fora do contexto familiar, como forma de compensação, pode afetar o bem estar psicológico ?', 'É bom sempre ter alguma figura de referência que podemos contar nos momentos bons e maus pois mostra a preocupação que os outros têm por nós a fazerem-nos sentir bem', 'Can seeking affection outside the family context as a form of compensation affect psychological well-being ?', 'It is important to have a reference figure we can trust and rely on in both good and difficult moments.', 'mental health'),
        (5, 'Quais são os maiores motivos para a diminuição da autoestima nos jovens e com que idades são mais frequentes ?', 'Principalmente pela insegurança da própria estética física, por volta dos 14 aos 17 (quando começamos a fazer as nossas perguntas)', 'What are the main reasons for decreased self-esteem among young people, and at what ages is this most common ?', 'Mainly due to concerns about physical appearance, most commonly between the ages of 14 and 17, when young people begin questioning themselves and their identity.', 'mental health')
    ''')

    conn.commit()
    conn.close()

    cursor.execute('''
        INSERT INTO questions (id_group, pergunta, resposta, question, answer, category) VALUES
        (6, 'Como podemos lidar com situações de stress ou de frustração no dia a dia ?', 'O stress é uma emoção que nem sempre é mau e tem pontos positivos e temos que saber lidar com a frustração no nosso dia a dia', 'How can we deal with situations of stress or frustration in daily life ?', 'stress is an emotion that is not always bad and has positive points and we have to know how to deal with frustration in our daily life', 'mental health'),
        (6, 'O que pode prejudicar a saúde mental de um adolescente ?', 'Ligar á opinião dos outros, ter relacionamentos abusivos, mau relacionamento com os celgas de turma ou de trabalho e ter autoestima baixa.', 'What can harm the mental health of a teenager ?', 'caring about others opinions, having abusive relationships, poor relationships with classmates or coworkers and having low self-esteem.', 'mental health'),
        (6, 'Como é que a escola pode contribuir para o bem-estar emocional dos alunos ?', 'A escola pode ajudar no convívio entre os colegas e professores e ajuda te a olhar para o teu futuro', 'How can school contribute to the emotional well-being of students ?', 'school can help with social interaction between classmates and teachers and helps you look toward your future', 'mental health'),
        (6, 'Como podemos identificar que um adolescente tem défice de atenção ?', 'Procurar sempre ajuda de médicos', 'How can we identify if a teenager has attention deficit ?', 'always seek help from doctors', 'mental health'),
        (6, 'Como é que a educação sexual pode contribuir para a prevenção de riscos ?', 'Prevenir se sempre para evitar as doenças sexualmente transmissíveis', 'How can sexual education contribute to risk prevention ?', 'always take precautions to avoid sexually transmitted diseases', 'prevention'),
        (6, 'Quais são os alimentos que devemos consumir com maior frequência ?', 'Os alimentos que devemos consumir com maior frequência são legumes e fruta devemos consumir fruta 1 ou 3 vezes por dia', 'Which foods should we consume most frequently ?', 'the foods we should consume most frequently are vegetables and fruit we should consume fruit 1 to 3 times a day', 'nutrition'),
        (6, 'Quais são os alimentos devemos evitar ou reduzir ?', 'Devemos evitar consumir doces, gorduras, salgados e comida processada', 'Which foods should we avoid or reduce ?', 'we should avoid consuming sweets, fats, salty snacks and processed food', 'nutrition'),
        (6, 'Como é que a atividade física contribui para a saúde do corpo e da mente ?', 'O exercício físico e a atividade física são muito importantes no dia a dia Reduz o stress e a ansiedade, Aumenta a resistência e a força muscular. Ajuda a manter um peso saudável.', 'How does physical activity contribute to the health of the body and mind ?', 'physical exercise and physical activity are very important in daily life It reduces stress and anxiety, Increases endurance and muscle strength. It helps maintain a healthy weight.', 'training'),
        (6, 'De que forma a autoestima influencia em relacionamentos afetivos, no trabalho ou nos estudos ?', 'É importante gostarmos de nós, e tentar valorizar naquilo que a gente tem, e tar com pessoas que nos ajude e nos faça sentir bem.', 'How does self-esteem influence romantic relationships, work or studies ?', 'it is important to like ourselves, and try to value what we have, and be with people who help us and make us feel good.', 'mental health'),
        (6, 'O uso de telemóvel antes de dormir influencia na qualidade do sono ?', 'Influencia pois é um estumolo visual', 'Does mobile phone use before sleep influence sleep quality ?', 'it influences it because it is a visual stimulus', 'prevention'),
        (6, 'Porque é que o sono é fundamental para o desenvolvimento cognitivo ?', 'Dormir a volta de 8 a 9 horas por dia', 'Why is sleep fundamental for cognitive development ?', 'Sleeping around 8 to 9 hours a day', 'prevention'),
        (6, 'Como podemos criar uma rotina saudável de descanso ?', 'Programar uma rotina de sono e devemos dormir sempre a mesma hora para que a tenhamos um bom descanso', 'How can we create a healthy rest routine ?', 'Schedule a sleep routine and we should always sleep at the same time so that we have a good rest', 'prevention'),
        (6, 'Quais são os principais riscos do tabaco vape e substâncias ilícitas para a saúde ?', 'São ríscos a nível físico, respiraório, mental, psicológico, social e mente a nossa vida em rísco', 'What are the main health risks of tobacco vape and illicit substances ?', 'They are risks at a physical, respiratory, mental, psychological, social level and puts our lives at risk', 'prevention')
    ''')

    conn.commit()
    conn.close()

    cursor.execute('''
    INSERT INTO questions (id_group, pergunta, resposta, question, answer, category) VALUES
    (7, 'É possível manter a saúde e ganhar massa muscular com uma dieta vegana ?', 'Sim, desde que se planeie o consumo de proteínas alternativas como leguminosas e frutos secos. A suplementação de Vitamina B12 é obrigatória por ser de origem animal. Atletas de MMA veganos demonstram que é possível manter ou até superar a massa magra de dietas comuns. O foco deve estar no equilíbrio entre massa gorda e muscular para manter a homeostase. A suplementação deve suprir défices específicos, como o ferro, sem substituir a alimentação.', 'Is it possible to maintain health and gain muscle on a vegan diet ?', 'Yes, as long as alternative protein sources like legumes and nuts are planned. Vitamin B12 supplementation is mandatory as it is animal-sourced. Vegan MMA athletes demonstrate that it is possible to maintain or even exceed the lean mass of standard diets. The focus should be on the balance between fat and muscle mass to maintain homeostasis. Supplementation should address specific deficits, such as iron, without replacing food.', 'nutrition'),
    (7, 'Como o treino de força e a massa muscular impactam o metabolismo e o envelhecimento ?', 'O treino de força transforma massa gorda em magra, especialmente em défice calórico. Mais músculo significa um metabolismo mais ativo e melhor controlo da glicemia, reduzindo riscos de diabetes e doenças cardiovasculares. Para idosos, o reforço muscular é vital para evitar quedas e fraturas. É um impacto físico e orgânico que protege as articulações. O corpo precisa de energia e massa muscular para prevenir lesões e manter o equilíbrio hormonal.', 'How do strength training and muscle mass impact metabolism and aging ?', 'Strength training transforms fat mass into lean mass, especially in a calorie deficit. More muscle means a more active metabolism and better glycemic control, reducing risks of diabetes and cardiovascular diseases. For the elderly, muscle strengthening is vital to prevent falls and fractures. It is a physical and organic impact that protects the joints. The body needs energy and muscle mass to prevent injuries and maintain hormonal balance.', 'training'),
    (7, 'Qual o perigo do consumo frequente de açúcar e álcool ?', 'O açúcar tem impacto viciante semelhante ao álcool e tabaco. O problema surge no consumo diário ou quando o doce substitui alimentos bons por questões emocionais, levando ao excesso calórico. Isso causa inflamação, cáries e doenças cardiovasculares, que são a principal causa de morte. Não existe dose benéfica de álcool ou açúcar. Deve-se evitar o ciclo de restrição semanal seguido de descontrole no fim de semana.', 'What is the danger of frequent sugar and alcohol consumption ?', 'Sugar has an addictive impact similar to alcohol and tobacco. The problem arises with daily consumption or when sweets replace good foods due to emotional issues, leading to calorie excess. This causes inflammation, cavities, and cardiovascular diseases, the leading cause of death. There is no beneficial dose of alcohol or sugar. One should avoid the cycle of weekly restriction followed by loss of control on the weekend.', 'nutrition'),
    (7, 'Qual a importância das proteínas, gorduras e da hidratação ?', 'Proteínas são os "tijolos" que constroem e reparam fibras musculares. As gorduras boas são essenciais para a produção de hormonas como a testosterona, absorção de vitaminas e energia. A água, que compõe 70% do corpo, regula a temperatura e transporta nutrientes. A desidratação causa fadiga, dores de cabeça e menor rendimento físico e cognitivo. Estes elementos garantem que a energia seja suprida e o corpo funcione de forma eficaz.', 'How important are proteins, fats, and hydration ?', 'Proteins are the "bricks" that build and repair muscle fibers. Good fats are essential for producing hormones like testosterone, vitamin absorption, and energy. Water, making up 70% of the body, regulates temperature and transports nutrients. Dehydration causes fatigue, headaches, and lower physical and cognitive performance. These elements ensure that energy is supplied and the body functions effectively.', 'nutrition'),
    (7, 'Como a rotina alimentar e a suplementação afetam o desempenho e o sono ?', 'Fazer 3 a 5 refeições diárias mantém a saciedade, energia e concentração. Refeições tardias (após as 21h) podem prejudicar o sono e a digestão, pois o ritmo circadiano abranda o corpo para o "shutdown". O sono ruim aumenta a fome no dia seguinte. Atualmente, a suplementação é recomendada até para quem não treina, visando o desempenho cognitivo. O objetivo é criar hábitos onde o doce seja ocasional, não uma rotina semanal.', 'How do eating routines and supplementation affect performance and sleep ?', 'Having 3 to 5 daily meals maintains satiety, energy, and concentration. Late meals (after 9 PM) can impair sleep and digestion as the circadian rhythm slows the body down for "shutdown". Poor sleep increases hunger the next day. Currently, supplementation is recommended even for those who don\'t train, focusing on cognitive performance. The goal is to create habits where sweets are occasional, not a weekly routine.', 'nutrition')
''')

    conn.commit()
    conn.close()
    
    cursor.execute('''
        INSERT INTO questions (id_group, pergunta, resposta, question, answer, category) VALUES
        (8, 'Qual a percentagem de jovens com doenças pulmonares por causa do tabaco ou com doenças relacionadas devido ao consumo de substâncias aditivas ?', 'Cerca de 16% dos jovens têm doenças pulmonares por causa do tabaco, e 10 em cada 100 desenvolvem problemas graves, como cancro no pulmão, devido ao consumo de substâncias aditivas.', 'What is the percentage of young people with lung diseases because of tobacco or with related diseases due to the consumption of addictive substances ?', 'About 16% of young people have lung diseases because of tobacco, and 10 in every 100 develop serious problems, such as lung cancer, due to the consumption of addictive substances.', 'Prevention'),
        (8, 'Qual a média de idade das pessoas que chegam com doenças relacionadas com o vício de bebidas alcoólicas ?', 'Quando o consumo de álcool é elevado e prolongado, os problemas de saúde costumam começar a aparecer por volta dos 40 anos.', 'What is the average age of people arriving with diseases related to addiction to alcoholic beverages ?', 'When alcohol consumption is high and prolonged, health problems usually start to appear around the age of 40.', 'Prevention'),
        (8, 'Quais são as maiores consequências para a sociedade (impacto social) desses comportamentos de dependências do tabaco, álcool e substâncias aditivas ?', 'Estas dependências acabam por aumentar doenças graves e criar problemas sociais como violência, acidentes e famílias desestruturadas.', 'What are the greatest consequences for society (social impact) of these behaviors of tobacco, alcohol and addictive substance dependencies ?', 'These dependencies end up increasing serious diseases and creating social problems such as violence, accidents, and broken families.', 'Prevention'),
        (8, 'Quais são as doenças mais frequentes relacionadas com substâncias aditivas ?', 'Pode causar cancro (principalmente no pulmão), doenças do fígado, problemas cardíacos, doenças respiratórias e também problemas mentais, como depressão e ansiedade.', 'What are the most frequent diseases related to addictive substances ?', 'It can cause cancer (mainly in the lungs), liver diseases, heart problems, respiratory diseases, and also mental problems such as depression and anxiety.', 'Prevention'),
        (8, 'Quais são os riscos e efeitos a curto prazo do consumo de tabaco e substâncias aditivas ?', 'O consumo pode causar problemas imediatos como cansaço, dificuldade em respirar e alterações no humor. Além disso, podem afetar o pulmão e o cérebro em desenvolvimento. Nos jovens, o risco é normalizar o vício, abrindo portas para problemas maiores no futuro.', 'What are the short-term risks and effects of tobacco and addictive substance consumption ?', 'Consumption can cause immediate problems such as fatigue, difficulty breathing, and mood swings. In addition, they can affect the lungs and the developing brain. In young people, the risk is normalizing the addiction, opening doors to bigger problems in the future.', 'Prevention'),
        (8, 'Os cigarros eletrónicos, como iqos e vapes, são menos prejudiciais para o ser humano em comparação com o cigarro normal ?', 'Ainda não se sabe completamente como os iqos e vapes atuam no corpo humano, por serem relativamente recentes. Os efeitos a longo prazo ainda não são totalmente conhecidos, mas já existem casos de problemas graves.', 'Are electronic cigarettes, such as iqos and vapes, less harmful to humans compared to regular cigarettes ?', 'It is not yet fully known how iqos and vapes act on the human body, as they are relatively recent. The long-term effects are not yet fully known, but there are already cases of serious problems.', 'Prevention'),
        (8, 'Quais os sintomas da infecção pulmonar provocada pelo tabaco ?', 'Os sintomas incluem muita tosse, febre e mal-estar, pois o pulmão fica mais vulnerável a infeções.', 'What are the symptoms of lung infection caused by tobacco ?', 'Symptoms include a lot of coughing, fever, and malaise, as the lung becomes more vulnerable to infections.', 'Prevention'),
        (8, 'Quais são os impactos prejudiciais para o indivíduo do consumo exagerado de bebidas alcoólicas ?', 'O álcool afeta o fígado e o cérebro, prejudica o raciocínio e pode causar dependência, tornando difícil parar.', 'What are the harmful impacts for the individual of excessive consumption of alcoholic beverages ?', 'Alcohol affects the liver and the brain, impairs reasoning, and can cause dependence, making it difficult to stop.', 'Prevention'),
        (8, 'Quais são os conselhos para deixar os vícios do consumo de tabaco ?', 'O melhor conselho é nunca começar.', 'What is the advice for quitting tobacco addictions ?', 'The best advice is never to start.', 'Prevention'),
        (8, 'Pode-se ter uma vida normal com o consumo moderado de substâncias psicoativas ?', 'Mesmo em pouca quantidade, existe sempre o risco de desenvolver problemas de saúde no futuro.', 'Can one have a normal life with moderate consumption of psychoactive substances ?', 'Even in small amounts, there is always a risk of developing health problems in the future.', 'Prevention'),
        (8, 'Quantas bebidas alcoólicas por semana são consideradas seguras para uma mulher e para um homem ?', 'Atualmente, a recomendação mais segura é não consumir álcool.', 'How many alcoholic drinks per week are considered safe for a woman and a man ?', 'Currently, the safest recommendation is not to consume alcohol.', 'Prevention'),
        (8, 'O que é ressaca? Como evitar e como resolver ?', 'A ressaca acontece devido à desidratação do corpo. Para aliviar, deve-se beber muita água. A forma mais eficaz de evitar é não consumir álcool.', 'What is a hangover? How to avoid it and how to solve it ?', 'A hangover happens due to the body\'s dehydration. To alleviate it, one should drink plenty of water. The most effective way to avoid it is not to consume alcohol.', 'Prevention')
    ''')

    conn.commit()
    conn.close()